### PR TITLE
fix: ast for division in calc

### LINKED ISSUE #56: invalid ast for `calc` with division
```css
width: calc(10px * 10px); // contains `word`, `space`, `word`, `space`, `word`
width: calc(10px / 10px); // contains `word`, `word`, `space`, `word` - i.e. no space before `/`
```

### PR DESCRIPTION
**Pull request by evilebottnawi**
fix #56

/cc @TrySound 

latest PR and we will update version in `stylelint`

### CODE REVIEW

File: test/parse.js [hunk 1]
```diff
@@ -492,6 +492,46 @@ var tests = [
       }
     ]
   },
+  {
+    message: "should correctly parse multiplication with spaces",
```
Comment (TrySound) [inline test/parse.js]: multiplication?

File: test/parse.js [hunk 2]
```diff
@@ -562,6 +642,36 @@ var tests = [
       }
     ]
   },
+  {
+    message: "should correctly parse multiplication without spaces",
```
Comment (TrySound) [inline test/parse.js]: division

File: test/parse.js [hunk 3]
```diff
@@ -532,6 +572,46 @@ var tests = [
       }
     ]
   },
+  {
+    message: "should correctly parse multiplication with spaces",
```
Comment (TrySound) [inline test/parse.js]: division
